- name: Install Git, Docker, Docker Compose, AWS CLI, and Docker Swarm Visualizer and System updates
  hosts: "*"
  become: true
  tasks:
    - name: Install system updates for centos systems
      yum:
        name: '*'
        state: latest
    
    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker dependencies
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Add Docker repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose
        executable: /bin/bash

    - name: Set execute permissions for Docker Compose
      file:
        path: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Install AWS CLI
      pip:
        name: awscli
        state: present

    - name: Install Docker Swarm Visualizer
      docker_compose:
        project_src: /opt/docker-swarm-visualizer
        project_name: swarm-visualizer
        build: no
        recreate_container: yes
        files:
          - docker-compose.yml
        state: present
      become: false
